"""Fixed Relationship

Revision ID: 5d9aaf81e4df
Revises: 
Create Date: 2019-03-30 22:25:39.691911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9aaf81e4df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_description'), 'status', ['description'], unique=True)
    op.create_index(op.f('ix_status_status'), 'status', ['status'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_description'), 'task', ['description'], unique=True)
    op.create_index(op.f('ix_task_task'), 'task', ['task'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('target_start_date', sa.DateTime(), nullable=True),
    sa.Column('target_end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_project_name'), 'project', ['project_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_task_task'), table_name='task')
    op.drop_index(op.f('ix_task_description'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_status_status'), table_name='status')
    op.drop_index(op.f('ix_status_description'), table_name='status')
    op.drop_table('status')
    # ### end Alembic commands ###
