"""added a column description

Revision ID: 74650372be19
Revises: 5d9aaf81e4df
Create Date: 2019-04-20 13:48:34.500597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74650372be19'
down_revision = '5d9aaf81e4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('description', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_project_description'), 'project', ['description'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_description'), table_name='project')
    op.drop_column('project', 'description')
    # ### end Alembic commands ###
